<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>PassiveScp127</RootNamespace>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp" Publicize="true" />
    <Reference Include="Assembly-CSharp-firstpass" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="UnityEngine.AudioModule" />
    <Reference Include="UnityEngine.PhysicsModule" />
    <Reference Include="CommandSystem.Core" />
    <Reference Include="Mirror" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Northwood.LabAPI" Version="1.1.7" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" PrivateAssets="all" />
  </ItemGroup>

</Project>
